### ISSUE TITLE
AWS cloud implementation

### ISSUE THREAD

**Issue by MariasStory** [kevoreilly/CAHI#13]
Dear authors,

Thank you for the cool idea of creating an easy to implement and deployment ready CAPEv2 solution.
Can you please consider to port the implementation to AWS cloud?

I would love to see it implemented in AWS Fargate, based on docker files.
Ansible is supported by AWS.

Sincerely

**Comment by doomedraven** [comment]
hello, imposible as we don't have AWS instances to test. So you will have to handle that by yourself
