### ISSUE TITLE
Is this project maintained?

### ISSUE THREAD

**Issue by acr-varonis** [kevoreilly/CAHI#22]
Hi, 
I wanted to ask if this project is maintained and if its up to date with the changes in https://github.com/kevoreilly/CAPEv2

Since I don't see many commits in this project i'm not sure if its up to date to reflect the recent update.

thank you

**Comment by doomedraven** [comment]
hello, no we don't dev this one, but it pulls changes from CAPEv2 when doing deployment. so it will be up to date with capev2, but if you will CAHI there is no support sadly
